import os

from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
SUPABASE_DB_URL = os.getenv("SUPABASE_DB_URL")
SUPABASE_DB = os.getenv("SUPABASE_DB")
SUPABASE_RESUME_BUCKET = os.getenv("SUPABASE_RESUME_BUCKET")

RESUME_LLM_MODEL = os.getenv("RESUME_LLM_MODEL")
INTERVIEW_LLM_MODEL = os.getenv("INTERVIEW_LLM_MODEL")
EVALUATION_LLM_MODEL = os.getenv("EVALUATION_LLM_MODEL")
OPENAI_KEY = os.getenv("OPENAI_API_KEY")

CALENDLY_MEETING_URL = os.getenv("CALENDLY_MEETING_URL")

VAPI_API_KEY = os.getenv("VAPI_API_KEY")
VAPI_API_BASE_URL = os.getenv("VAPI_API_BASE_URL")
VAPI_PHONE_NUMBER_ID = os.getenv("VAPI_PHONE_NUMBER_ID")
VAPI_RECRUITER_ASSISTANT_ID = os.getenv("VAPI_RECRUITER_ASSISTANT_ID")
VAPI_INTERVIEW_WEBHOOK_URL = os.getenv("VAPI_INTERVIEW_WEBHOOK_URL")
VAPI_CALL_WEBHOOK_URL = os.getenv("VAPI_CALL_WEBHOOK_URL")

COMPANY_NAME = os.getenv("COMPANY_NAME")
COMPANY_DESCRIPTION = os.getenv("COMPANY_DESCRIPTION")
CLIENT_NAME = os.getenv("CLIENT_NAME")
CLIENT_DESCRIPTION = os.getenv("CLIENT_DESCRIPTION")

ROLE_TITLE = os.getenv("ROLE_TITLE")
ROLE_STACK = os.getenv("ROLE_STACK")
ROLE_LOCATION = os.getenv("ROLE_LOCATION")
ROLE_SCHEDULE = os.getenv("ROLE_SCHEDULE")
INTERVIEW_DURATION = os.getenv("INTERVIEW_DURATION")

APSCHEDULER_DB_NAME = os.getenv("APSCHEDULER_DB_NAME")

APPLICATION_BASE_URL = os.getenv("APPLICATION_BASE_URL")
APPLICATION_PORT = int(os.getenv("APPLICATION_PORT"))
